# config.yaml
database:
  dbname: "nom_database"
  user: "nom_utilisateur"
  password: "mot_de_passe"
  host: "host_database"
  port: 0000

api:
  model: "nom_model"
  temperature: 0
  cle_api: "cle_api"