# config.yaml
database:
  dbname: "postgres"
  user: "postgres"
  password: "carving-footnote-dividend-geriatric"
  host: "db.itkvotbgocuzitxxiwtx.supabase.co"
  port: 5432

api:
  model: "llama-3.3-70b-versatile"
  temperature: 0
  cle_api: "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"