# config.yaml
database:
  connection_string: "db_connexion"
  dbname: "database_name"
  user: "user_name"
  password: "password"
  host: "host_database"
  port: 0000

api:
  model: "model_name"
  temperature: 0
  api_key: "api_key"

admin:
  password: "admin_password"